"""get direction to ExchangeItem

Revision ID: 84055d5a9dad
Revises: f434cd8da085
Create Date: 2025-04-12 14:09:34.146299

"""
from typing import Sequence, Union

import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84055d5a9dad'
down_revision: Union[str, None] = 'f434cd8da085'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE directiontype AS ENUM ('given', 'received')")
    op.add_column('exchangeitem', sa.Column('direction', sa.Enum('given', 'received', name='directiontype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchangeitem', 'direction')
    op.execute("DROP TYPE directiontype")
    # ### end Alembic commands ###
