"""set None field

Revision ID: cd74fa0a30b7
Revises: 84055d5a9dad
Create Date: 2025-04-12 15:31:14.845423

"""
from typing import Sequence, Union

import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd74fa0a30b7'
down_revision: Union[str, None] = '84055d5a9dad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'author',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('book', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('book', 'genre',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('book', 'language',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('book', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('book', 'language',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('book', 'genre',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('book', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('book', 'author',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
